---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bot-secrets
  namespace: default
spec:
  encryptedData:
    DISCORD_TOKEN: AgAq5OthbCVxkxrlfr3v7lqyz+Zxdxd5CjpGNargYcUfr1tZP+g/JBj2UE0eHOLUCqTRqSKsbrm+Lms9m6wNbSqrTMyUZiYB3dYDVpryLJo0kCvCNiYuzbbtMTCmtyMxuDezo93njAkAAA3PwxPEBwZO+o4SFRiif528ldwXnFDIILFI+W+Lr9YyKBr0i0DdibQTsjBfgoT0YUKmkgU79YrZZBdQMkMIIYdanDgB0aXmb6QjZHL5oTPl1JFik+9ouNH6Y6bwFV1hR0m+yEWX+VeY5ZCmDMgv3tD2dwArdfhdaacvR6j7H60HDU9z1MPW9ALUISt/g3ctmifIPqI6yey3xZPEoRtUGwu5BscnqZfzj5PrjSk2dKMfPSR/c5ewrF6+EMTIiY9+cv2rxZWnTB6wbQIttLLcQVIHEaBA/i3OGsqxmL/YTDQFjwNqjJK+tNnUh2cLpBJEtZfVmn/DWiZIpO4nN80xe7AUO8/01ODgFHphaI3SoqCTyPPE9reat96RTw2StWe0bbu1h6DWgZhWQy/PB0fNMFaQ/9oqe3NC5Vq1yYHDRZ7HFalFYGufih37rW0rw4zSrfT9T1jwWBrjeUwSD/P2mmiAXLSpQUoYAo7IyG5n9Ot5vM3LENm55sDZ/LWGtZiqQecSjinCWRVdBti5f8yB8Wcm9J7k6CgsNWlm8uzAQ1SlPYbKJvr40MYn5uUF2p9gaVY6Yj3vC5E=
  template:
    metadata:
      name: bot-secrets
      namespace: default
