// <auto-generated />
using JohnVGDCBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JohnVGDCBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260518103544_AddReminderGroupCreatorId")]
    partial class AddReminderGroupCreatorId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("JohnVGDCBot.ReminderGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReminderGroups");
                });

            modelBuilder.Entity("JohnVGDCBot.ReminderGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReminderGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReminderGroupId");

                    b.ToTable("ReminderGroupMembers");
                });

            modelBuilder.Entity("JohnVGDCBot.ReminderGroupMember", b =>
                {
                    b.HasOne("JohnVGDCBot.ReminderGroup", "ReminderGroup")
                        .WithMany("Members")
                        .HasForeignKey("ReminderGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReminderGroup");
                });

            modelBuilder.Entity("JohnVGDCBot.ReminderGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
